version: "3"
services:
  python:
    build: .
    container_name: scrapy
    tty: true
    volumes:
      - ./:/app
  pinnacle:
    build:
      context: .
      dockerfile: Dockerfile.pinnacle
    container_name: pinnacle
    env_file:
    - .env
    tty: true
    volumes:
      - ./:/app
