EXPLANATORY_VARIABLES = [
    'player1_H2H',
    # 'player1_age',
    'player1_career_surface_lose',
    'player1_career_surface_win',
    'player1_career_total_lose',
    'player1_career_total_win',
    # 'player1_current_rank',
    # 'player1_elo',
    'player1_height',
    # 'player1_highest_rank',
    'player1_odds',
    'player1_roi',
    # 'player1_year_surface_lose',
    # 'player1_year_surface_win',
    # 'player1_year_total_lose',
    # 'player1_year_total_win',
    'player2_H2H',
    # 'player2_age',
    'player2_career_surface_lose',
    'player2_career_surface_win',
    'player2_career_total_lose',
    'player2_career_total_win',
    # 'player2_current_rank',
    # 'player2_elo',
    'player2_height',
    # 'player2_highest_rank',
    'player2_odds',
    'player2_roi',
    # 'player2_year_surface_lose',
    # 'player2_year_surface_win',
    # 'player2_year_total_lose',
    # 'player2_year_total_win',
    'winner'
]
