name: GetNext24HrsMatches

on:
  schedule:
    - cron: "0 0/3 * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libgomp1
        run: sudo apt-get install libgomp1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Answer Cralwer
        run: scrapy crawl answer
      - name: Join CSV
        run: python join_csv.py
      - name: Update OLS Model
        run: python analyze.py
      - name: Run Matches Cralwer
        run: scrapy crawl matches
      - name: git setting
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
      - name: Commit files
        run: |
          git add .
          git commit -m "Update Match Schedules" -a
          git pull origin main --rebase
          git push origin main
      - name: dispatch update-packages
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ebijun1007/blog_luden
          token: ${{ secrets.PERSONAL_TOKEN }}
          event-type: build
  bet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libgomp1
        run: sudo apt-get install libgomp1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install requests slackweb pandas
          pip3 install pinnacle
      - name: bet
        run: python pinnacle_client.py
